#!/usr/bin/env python3
# This file is part of Nuntiare project.
# The COPYRIGHT file at the top level of this repository
# contains the full copyright notices and license terms.
import os
import sys
import argparse
import logging

try:
    from nuntiare import (PROJECT_NAME, DESCRIPTION, VERSION,
                          COPYRIGHT, LICENSE, LOGGER)
except ImportError:
    print('Running uninstalled mode...')
    DIR = os.path.dirname(os.path.realpath(__file__))
    DIR = os.path.normpath(os.path.join(DIR, '..', 'nuntiare'))
    if os.path.isdir(DIR):
        sys.path.insert(0, os.path.dirname(DIR))
    from nuntiare import (PROJECT_NAME, DESCRIPTION, VERSION,
                          COPYRIGHT, LICENSE, LOGGER)


APPNAME = PROJECT_NAME + ' command line tool'

if sys.stdout:
    LOGGER.add_handler(logging.StreamHandler(sys.stdout),
                       level='WARNING', name='stdout')


def get_info():
    res = "\n{0} version {1}\nCopyright {2}\nLicensed under {3}".format(
        APPNAME, VERSION, COPYRIGHT, LICENSE)
    return res


def verify_file(file):
    if not os.path.isfile(file) or not os.access(file, os.R_OK):
        err_msg = "'{0}' is not a valid file or " \
            "user has not read access for it."
        LOGGER.error(err_msg.format(file), True, 'IOError')


def do_render(args):
    from nuntiare.report import Report
    from nuntiare.render.render import Render

    def get_parameters(params):
        if params is None:
            return
        result = {}
        for p in params:
            i = p.find('=')
            if i < 1:
                LOGGER.warn(
                    "Parameter in wrong format: '{0}'. Ignored.".format(p))
                continue
            name = p[:i]
            val = p[i+1:]
            result[name] = val
        return result

    if args.v != 'WARNING':
        lg = LOGGER.get_handler('stdout')
        lg.setLevel(LOGGER._get_level_from_string(args.v))

    verify_file(args.file)

    renders = args.r
    if not renders:
        if args.save:
            renders = []
        else:
            renders = ['html']  # Default render

    report = Report(
        args.file, output_name=args.o,
        output_directory=args.d)

    report.run(get_parameters(args.p))

    for r in renders:
        render = Render.get_render(r)
        if not render:
            LOGGER.warn(
                "Render '{0}' not found.".format(r))
            continue
        #render.render(report, not args.no_overwrite)
        evw = False
        render.render(report, {'overwrite': not args.no_overwrite})

    if args.save:
        report.save(not args.no_overwrite)


def do_embed_image(args):
    verify_file(args.file)
    verify_file(args.image)

    from nuntiare.definition.element import EmbeddedImages

    filename, ext = os.path.splitext(os.path.basename(args.image))

    if args.n:
        name = args.n
    else:
        name = filename

    if args.m:
        mimetype = args.m
    else:
        ext = ext.lower()[1:]
        if ext == 'bmp':
            mimetype = 'image/bmp'
        elif ext in ['jpg', 'jpeg']:
            mimetype = 'image/jpeg'
        elif ext == 'gif':
            mimetype = 'image/gif'
        elif ext == 'png':
            mimetype = 'image/png'
        else:
            LOGGER.error(
                "MIMEType can not be inferred from '{0}' extension".format(
                    ext), raise_error=True)

    EmbeddedImages.embed_image_file(args.file, args.image, name, mimetype)


def run():
    # ======== parser ==================
    parser = argparse.ArgumentParser(
        description='Nuntiare command line tool',
        formatter_class=argparse.RawTextHelpFormatter)

    parser.add_argument(
        "-i", "--info", action='version', version=get_info(),
        help='Show version, copyright and license.')

    subparsers = parser.add_subparsers(dest='command')

    # ======== render ==================
    help = "Performs a rendering process " \
        "for a nuntiare xml definition file."
    parser_render = subparsers.add_parser(
        'render',
        formatter_class=argparse.RawTextHelpFormatter,
        description=help)

    help = 'Nuntiare xml definition file to process.'
    parser_render.add_argument("file", help=help)

    help = "List of parameters in 'name=value' " \
        "form.\nEx: -p param1=2 'param2=a b c' param3=value3."
    parser_render.add_argument(
        "-p", metavar="parameters", nargs='+', help=help)

    help = "List of rendering types. Ex: pdf html csv." \
        "\nSee nuntiare.cfg for definitions.\nDefault: 'html'"
    parser_render.add_argument(
        "-r", metavar="render", nargs='+', help=help)

    help = "Output file name without extension." \
        "\nDefault: xml report definition file name."
    parser_render.add_argument("-o", metavar="output", help=help)

    help = "Directory where output file will be located." \
        "\nDefault: xml report definition file directory."
    parser_render.add_argument(
        "-d", metavar="directory", help=help)

    help = "No overwrites resulting file, if it exists."
    parser_render.add_argument(
        "--no-overwrite", action='store_true', help=help)

    help = "Append dataset records to definition " \
        "\nand saves it in a new file with .nuntiare extension."
    parser_render.add_argument(
        "--save", action='store_true', help=help)

    help = "Logs output verbosity. Default: 'WARNING'"
    parser_render.add_argument(
        "-v", choices=["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"],
        default="WARNING", help=help)

    # ======== embed image ==================
    help = 'Embed an image into a xml definition file as base64 string.'
    parser_embed_image = subparsers.add_parser(
        'embed-image',
        formatter_class=argparse.RawTextHelpFormatter,
        description=help)

    help = 'Nuntiare xml definition file where image will be embedded.'
    parser_embed_image.add_argument("file", help=help)

    help = 'Image which will be embedded.'
    parser_embed_image.add_argument("image", help=help)

    help = "Element name for image in Nuntiare xml definition file. " \
            "\nDefault: Image file name."
    parser_embed_image.add_argument(
        "-n", metavar="name", help=help)

    help = "Valid image MIMEType." \
            "\nDefault: Inferred from image file extension."
    parser_embed_image.add_argument(
        "-m", choices=[
            'image/bmp', 'image/jpeg',
            'image/gif', 'image/png', 'image/xpng'
            ], help=help)

    # ====================================

    args = parser.parse_args()

    if args.command == 'render':
        do_render(args)
    elif args.command == 'embed-image':
        do_embed_image(args)


if __name__ == "__main__":
    run()
