#!/usr/bin/env python
# This file is part of Nuntiare project.
# The COPYRIGHT file at the top level of this repository
# contains the full copyright notices and license terms.

import os
import sys

try:
    from nuntiare.pluma import Pluma
except ImportError:
    print('Running uninstalled mode...')
    DIR = os.path.dirname(os.path.realpath(__file__))
    DIR = os.path.normpath(os.path.join(DIR, '..', 'nuntiare'))
    if os.path.isdir(DIR):
        sys.path.insert(0, os.path.dirname(DIR))
    from nuntiare.pluma import Pluma


if __name__ == '__main__':
    pluma = Pluma()
    pluma.run()
