# This file is part of Nuntiare project.
# The COYRIGHT file at the top level of this repository
# contains the full copyright notices and license terms.

import unittest
import dateutil
import math
from decimal import Decimal
from nuntiare.outcome.page_tablix import Grid


class GridTest(unittest.TestCase):
    def testGrid(self):
        # Grow in column direction first
        grid = Grid()
        self._check_grid(grid, 0, 0)
        grid.add_cell(0, 0, "0-0")
        self._check_cell(grid, 0, 0, "0-0")
        self._check_grid(grid, 1, 1)
        grid.add_cell(0, 1, "0-1")
        self._check_cell(grid, 0, 1, "0-1")
        self._check_grid(grid, 1, 2)
        grid.add_cell(0, 2, "0-2")
        self._check_cell(grid, 0, 2, "0-2")
        self._check_grid(grid, 1, 3)
        grid.add_cell(1, 0, "1-0")
        self._check_cell(grid, 1, 0, "1-0")
        self._check_cell(grid, 1, 1, None)
        self._check_cell(grid, 1, 2, None)
        self._check_grid(grid, 2, 3)
        grid.add_cell(1, 1, "1-1")
        self._check_cell(grid, 1, 1, "1-1")
        self._check_cell(grid, 1, 2, None)
        self._check_grid(grid, 2, 3)
        grid.add_cell(1, 2, "1-2")
        self._check_cell(grid, 1, 2, "1-2")
        self._check_grid(grid, 2, 3)
        grid.add_cell(2, 0, "2-0")
        self._check_cell(grid, 2, 0, "2-0")
        self._check_cell(grid, 2, 1, None)
        self._check_cell(grid, 2, 2, None)
        self._check_grid(grid, 3, 3)
        grid.add_cell(2, 1, "2-1")
        self._check_cell(grid, 2, 1, "2-1")
        self._check_cell(grid, 2, 2, None)
        self._check_grid(grid, 3, 3)
        grid.add_cell(2, 2, "2-2")
        self._check_cell(grid, 2, 2, "2-2")
        self._check_grid(grid, 3, 3)

        self._check_cell(grid, 0, 0, "0-0")
        self._check_cell(grid, 0, 1, "0-1")
        self._check_cell(grid, 0, 2, "0-2")
        self._check_cell(grid, 1, 0, "1-0")
        self._check_cell(grid, 1, 1, "1-1")
        self._check_cell(grid, 1, 2, "1-2")
        self._check_cell(grid, 2, 0, "2-0")
        self._check_cell(grid, 2, 1, "2-1")
        self._check_cell(grid, 2, 2, "2-2")
        self._check_grid(grid, 3, 3)

        # Grow in row first
        grid = Grid()
        self._check_grid(grid, 0, 0)
        grid.add_cell(0, 0, "0-0")
        self._check_cell(grid, 0, 0, "0-0")
        self._check_grid(grid, 1, 1)
        grid.add_cell(1, 0, "1-0")
        self._check_cell(grid, 1, 0, "1-0")
        self._check_grid(grid, 2, 1)
        grid.add_cell(2, 0, "2-0")
        self._check_cell(grid, 2, 0, "2-0")
        self._check_grid(grid, 3, 1)
        grid.add_cell(0, 1, "0-1")
        self._check_cell(grid, 0, 1, "0-1")
        self._check_cell(grid, 1, 1, None)
        self._check_cell(grid, 2, 1, None)
        self._check_grid(grid, 3, 2)
        grid.add_cell(1, 1, "1-1")
        self._check_cell(grid, 1, 1, "1-1")
        self._check_cell(grid, 2, 1, None)
        self._check_grid(grid, 3, 2)
        grid.add_cell(2, 1, "2-1")
        self._check_cell(grid, 2, 1, "2-1")
        self._check_grid(grid, 3, 2)
        grid.add_cell(0, 2, "0-2")
        self._check_cell(grid, 0, 2, "0-2")
        self._check_cell(grid, 1, 2, None)
        self._check_cell(grid, 2, 2, None)
        self._check_grid(grid, 3, 3)
        grid.add_cell(1, 2, "1-2")
        self._check_cell(grid, 0, 2, "0-2")
        self._check_cell(grid, 1, 2, "1-2")
        self._check_cell(grid, 2, 2, None)
        self._check_grid(grid, 3, 3)
        grid.add_cell(2, 2, "2-2")
        self._check_cell(grid, 0, 2, "0-2")
        self._check_cell(grid, 1, 2, "1-2")
        self._check_cell(grid, 2, 2, "2-2")
        self._check_grid(grid, 3, 3)

        # Span
        grid = Grid()
        grid.add_cell(0, 0, "0-0")
        grid.add_cell(0, 1, "0-1")
        grid.add_cell(0, 2, "0-2")
        grid.add_cell(0, 3, "0-3")
        grid.add_cell(1, 0, "1-0")
        # ColSpan
        grid.add_cell(1, 1, "1-1", col_span=2)
        self._check_cell(grid, 1, 1, "1-1", col_span=2)
        self._check_cell(grid, 1, 2, "1-1", col_span=2)
        self._check_cell(grid, 1, 3, None)
        grid.add_cell(1, 3, "1-3")
        self._check_grid(grid, 2, 4)
        grid.add_cell(2, 0, "2-0")
        grid.add_cell(2, 1, "2-1")
        # RowSpan
        grid.add_cell(2, 2, "2-2", row_span=2)
        self._check_grid(grid, 4, 4)
        self._check_cell(grid, 2, 2, "2-2", row_span=2)
        self._check_cell(grid, 3, 2, "2-2", row_span=2)
        self._check_cell(grid, 3, 0, None)
        grid.add_cell(2, 3, "2-3")
        grid.add_cell(3, 0, "3-0")
        self._check_cell(grid, 3, 0, "3-0")
        grid.add_cell(3, 1, "3-1")
        grid.add_cell(3, 3, "3-3")
        grid.add_cell(4, 0, "4-0")
        grid.add_cell(4, 1, "4-1")
        grid.add_cell(4, 2, "4-2")
        grid.add_cell(4, 3, "4-3")
        self._check_grid(grid, 5, 4)

        # ColSpan and RowSpan
        grid = Grid()
        grid.add_cell(0, 0, "0-0")
        grid.add_cell(0, 1, "0-1")
        grid.add_cell(0, 2, "0-2")
        grid.add_cell(0, 3, "0-3")
        grid.add_cell(0, 4, "0-4")
        grid.add_cell(1, 0, "1-0")

        grid.add_cell(1, 1, "1-1", row_span=3, col_span=3)
        self._check_grid(grid, 4, 5)
        self._check_cell(grid, 1, 4, None)
        self._check_cell(grid, 2, 0, None)
        self._check_cell(grid, 2, 4, None)
        self._check_cell(grid, 3, 0, None)
        self._check_cell(grid, 3, 4, None)
        self._check_cell(grid, 1, 1, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 1, 2, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 1, 3, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 2, 1, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 3, 1, "1-1", row_span=3, col_span=3)
        # Intersection
        self._check_cell(grid, 2, 2, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 2, 3, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 3, 2, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 3, 3, "1-1", row_span=3, col_span=3)

        grid.add_cell(1, 4, "1-4")
        grid.add_cell(2, 0, "2-0")
        grid.add_cell(2, 4, "2-4")
        grid.add_cell(3, 0, "3-0")
        grid.add_cell(3, 4, "3-4")
        grid.add_cell(4, 0, "4-0")
        grid.add_cell(4, 1, "4-1")
        grid.add_cell(4, 2, "4-2")
        grid.add_cell(4, 3, "4-3")
        grid.add_cell(4, 4, "4-4")

        # Last check
        self._check_grid(grid, 5, 5)
        self._check_cell(grid, 0, 0, "0-0")
        self._check_cell(grid, 0, 1, "0-1")
        self._check_cell(grid, 0, 2, "0-2")
        self._check_cell(grid, 0, 3, "0-3")
        self._check_cell(grid, 0, 4, "0-4")
        self._check_cell(grid, 1, 0, "1-0")
        self._check_cell(grid, 1, 1, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 1, 2, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 1, 3, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 1, 4, "1-4")
        self._check_cell(grid, 2, 0, "2-0")
        self._check_cell(grid, 2, 1, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 2, 2, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 2, 3, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 2, 4, "2-4")
        self._check_cell(grid, 3, 0, "3-0")
        self._check_cell(grid, 3, 1, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 3, 2, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 3, 3, "1-1", row_span=3, col_span=3)
        self._check_cell(grid, 3, 4, "3-4")
        self._check_cell(grid, 4, 0, "4-0")
        self._check_cell(grid, 4, 1, "4-1")
        self._check_cell(grid, 4, 2, "4-2")
        self._check_cell(grid, 4, 3, "4-3")
        self._check_cell(grid, 4, 4, "4-4")

        # Span automatically

        # Grow direction: Column
        grid = Grid(grow_direction="column")
        self._check_grid(grid, 0, 0)
        cell_0_0 = grid.add_cell(0, 0, "0-0")
        self._check_grid(grid, 1, 1)
        self._check_cell(grid, 0, 0, "0-0")
        cell_1_0 = grid.add_cell(1, 0, "1-0", parent_cell=cell_0_0)
        self._check_grid(grid, 2, 1)
        self._check_cell(grid, 1, 0, "1-0")
        self.assertEqual(cell_0_0.col_span, 1)
        cell_2_0 = grid.add_cell(2, 0, "2-0", parent_cell=cell_1_0)
        self._check_grid(grid, 3, 1)
        self._check_cell(grid, 2, 0, "2-0")
        self.assertEqual(cell_0_0.col_span, 1)
        cell_3_0 = grid.add_cell(3, 0, "3-0", parent_cell=cell_2_0)
        self._check_grid(grid, 4, 1)
        self._check_cell(grid, 3, 0, "3-0")
        self.assertEqual(cell_0_0.col_span, 1)
        cell_3_1 = grid.add_cell(3, 1, "3-1", parent_cell=cell_2_0)
        self._check_grid(grid, 4, 2)
        self._check_cell(grid, 3, 1, "3-1")
        self._check_cell(grid, 0, 0, "0-0", col_span=2)
        self._check_cell(grid, 0, 1, "0-0", col_span=2)
        self._check_cell(grid, 1, 0, "1-0", col_span=2)
        self._check_cell(grid, 1, 1, "1-0", col_span=2)
        self._check_cell(grid, 2, 0, "2-0", col_span=2)
        self._check_cell(grid, 2, 1, "2-0", col_span=2)
        cell_3_2 = grid.add_cell(3, 2, "3-2", parent_cell=cell_2_0)
        self._check_grid(grid, 4, 3)
        self._check_cell(grid, 3, 2, "3-2")
        self._check_cell(grid, 0, 0, "0-0", col_span=3)
        self._check_cell(grid, 0, 1, "0-0", col_span=3)
        self._check_cell(grid, 0, 2, "0-0", col_span=3)
        self._check_cell(grid, 1, 0, "1-0", col_span=3)
        self._check_cell(grid, 1, 1, "1-0", col_span=3)
        self._check_cell(grid, 1, 2, "1-0", col_span=3)
        self._check_cell(grid, 2, 0, "2-0", col_span=3)
        self._check_cell(grid, 2, 1, "2-0", col_span=3)
        self._check_cell(grid, 2, 2, "2-0", col_span=3)

        next_col = grid.next_column()
        self.assertEqual(next_col, 3)
        cell_1_1 = grid.add_cell(1, next_col, "1-1", parent_cell=cell_0_0)
        self._check_grid(grid, 4, 4)
        self._check_cell(grid, 1, 3, "1-1")
        self.assertEqual(cell_0_0.col_span, 4)

        cell_2_1 = grid.add_cell(2, next_col, "2-1", parent_cell=cell_1_1)
        self._check_grid(grid, 4, 4)
        self._check_cell(grid, 1, 3, "1-1")
        self.assertEqual(cell_0_0.col_span, 4)

        cell_3_3 = grid.add_cell(3, next_col, "3-3", parent_cell=cell_2_1)
        self._check_grid(grid, 4, 4)
        self._check_cell(grid, 3, 3, "3-3")
        self.assertEqual(cell_0_0.col_span, 4)

        cell_3_4 = grid.add_cell(3, next_col + 1, "3-4", parent_cell=cell_2_1)
        self._check_grid(grid, 4, 5)
        self._check_cell(grid, 3, 4, "3-4")
        self.assertEqual(cell_0_0.col_span, 5)

        # Grow direction: Row (Default)
        grid = Grid()
        self._check_grid(grid, 0, 0)
        cell_0_0 = grid.add_cell(0, 0, "0-0")

        cell_0_1 = grid.add_cell(0, 1, "0-1", parent_cell=cell_0_0)
        self._check_grid(grid, 1, 2)
        self._check_cell(grid, 0, 1, "0-1")
        cell_0_2 = grid.add_cell(0, 2, "0-2", parent_cell=cell_0_1)
        self._check_grid(grid, 1, 3)
        self._check_cell(grid, 0, 2, "0-2")

        cell_0_3 = grid.add_cell(0, 3, "0-3", parent_cell=cell_0_2)
        self._check_grid(grid, 1, 4)
        self._check_cell(grid, 0, 3, "0-3")
        self._check_cell(grid, 0, 0, "0-0")
        next_row = grid.next_row()
        self.assertEqual(next_row, 1)
        cell_1_3 = grid.add_cell(next_row, 3, "1-3", parent_cell=cell_0_2)
        self._check_grid(grid, 2, 4)
        self._check_cell(grid, 1, 3, "1-3")
        self._check_cell(grid, 0, 2, "0-2", row_span=2)
        self._check_cell(grid, 1, 2, "0-2", row_span=2)
        cell_2_3 = grid.add_cell(next_row + 1, 3, "2-3", parent_cell=cell_0_2)
        self._check_grid(grid, 3, 4)
        self._check_cell(grid, 2, 3, "2-3")
        self._check_cell(grid, 0, 2, "0-2", row_span=3)
        self._check_cell(grid, 1, 2, "0-2", row_span=3)
        self._check_cell(grid, 2, 2, "0-2", row_span=3)
        self._check_cell(grid, 0, 0, "0-0", row_span=3)
        self._check_cell(grid, 1, 0, "0-0", row_span=3)
        self._check_cell(grid, 2, 0, "0-0", row_span=3)

        next_row = grid.next_row()
        self.assertEqual(next_row, 3)
        cell_1_1 = grid.add_cell(next_row, 1, "1-1", parent_cell=cell_0_0)
        self._check_grid(grid, 4, 4)
        self._check_cell(grid, 3, 1, "1-1")

        cell_1_2 = grid.add_cell(next_row, 2, "1-2", parent_cell=cell_1_1)
        self._check_grid(grid, 4, 4)
        self._check_cell(grid, 3, 2, "1-2")

        cell_3_3 = grid.add_cell(next_row, 3, "3-3", parent_cell=cell_1_2)
        self._check_grid(grid, 4, 4)
        self._check_cell(grid, 3, 3, "3-3")
        cell_3_4 = grid.add_cell(next_row + 1, 3, "3-4", parent_cell=cell_1_2)
        self._check_grid(grid, 5, 4)
        self._check_cell(grid, 4, 3, "3-4")

        self._check_cell(grid, 0, 0, "0-0", row_span=5)
        self._check_cell(grid, 1, 0, "0-0", row_span=5)
        self._check_cell(grid, 2, 0, "0-0", row_span=5)
        self._check_cell(grid, 3, 0, "0-0", row_span=5)
        self._check_cell(grid, 4, 0, "0-0", row_span=5)

        self._check_cell(grid, 0, 1, "0-1", row_span=3)
        self._check_cell(grid, 1, 1, "0-1", row_span=3)
        self._check_cell(grid, 2, 1, "0-1", row_span=3)

        self._check_cell(grid, 3, 1, "1-1", row_span=2)
        self._check_cell(grid, 4, 1, "1-1", row_span=2)

        self._check_cell(grid, 0, 2, "0-2", row_span=3)
        self._check_cell(grid, 1, 2, "0-2", row_span=3)
        self._check_cell(grid, 2, 2, "0-2", row_span=3)

        self._check_cell(grid, 3, 2, "1-2", row_span=2)
        self._check_cell(grid, 4, 2, "1-2", row_span=2)

        # ======== Extend ===========

        grid_A = Grid()
        grid_A.add_cell(0, 0, "A-0-0")
        grid_A.add_cell(0, 1, "A-0-1")
        grid_A.add_cell(0, 2, "A-0-2")
        grid_A.add_cell(1, 0, "A-1-0")
        grid_A.add_cell(1, 1, "A-1-1")
        grid_A.add_cell(1, 2, "A-1-2")
        grid_A.add_cell(2, 0, "A-2-0")
        grid_A.add_cell(2, 1, "A-2-1")
        grid_A.add_cell(2, 2, "A-2-2")

        grid_B = Grid()
        grid_B.add_cell(0, 0, "B-0-0")
        grid_B.add_cell(0, 1, "B-0-1")
        grid_B.add_cell(0, 2, "B-0-2")
        grid_B.add_cell(1, 0, "B-1-0")
        grid_B.add_cell(1, 1, "B-1-1")
        grid_B.add_cell(1, 2, "B-1-2")
        grid_B.add_cell(2, 0, "B-2-0")
        grid_B.add_cell(2, 1, "B-2-1")
        grid_B.add_cell(2, 2, "B-2-2")

        grid_A.extend(grid_B, "right")
        self._check_grid(grid_A, 3, 6)
        self._check_cell(grid_A, 0, 0, "A-0-0")
        self._check_cell(grid_A, 0, 3, "B-0-0")
        self._check_cell(grid_A, 2, 5, "B-2-2")

        grid_A = Grid()
        grid_A.add_cell(0, 0, "A-0-0")
        grid_A.add_cell(0, 1, "A-0-1")
        grid_A.add_cell(0, 2, "A-0-2")
        grid_A.add_cell(1, 0, "A-1-0")
        grid_A.add_cell(1, 1, "A-1-1")
        grid_A.add_cell(1, 2, "A-1-2")
        grid_A.add_cell(2, 0, "A-2-0")
        grid_A.add_cell(2, 1, "A-2-1")
        grid_A.add_cell(2, 2, "A-2-2")

        grid_A.extend(grid_B, "down")
        self._check_grid(grid_A, 6, 3)
        self._check_cell(grid_A, 0, 0, "A-0-0")
        self._check_cell(grid_A, 3, 0, "B-0-0")
        self._check_cell(grid_A, 5, 2, "B-2-2")

    def _check_grid(self, grid, row_count, column_count):
        self.assertEqual(len(grid.rows), row_count)
        self.assertEqual(len(grid.columns), column_count)

    def _check_cell(
            self, grid, row_index, column_index,
            object_value, row_span=1, col_span=1):
        cell = grid.get_cell(row_index, column_index)
        if object_value is None:
            self.assertEqual(cell, object_value)
            return cell
        self.assertEqual(cell.object, object_value)
        self.assertEqual(cell.row_span, row_span)
        self.assertEqual(cell.col_span, col_span)
        return cell
